### PR TITLE
Update onefile-maker-windows.py

### PR DESCRIPTION
**Pull request by deajan**
New version allows:

- Tuning LZMA dict size for NSIS
- Automagically remove unnecessary Nuitka & tkinter files (removing about 900 files, making startup like 5 seconds faster on SSD)
- Allow UAC privilege set
- Allow optional icon for output file

### CODE REVIEW

**Comment by deajan** [comment]
@JorjMcKie I've finished polishing the windows one file creator for Nuitka.
I've ported another of my nuitka functions I use in my toolchains, which removes most of Tkinter files, and some of the Nuitka files which in most cases are unused. That makes the SFX (a bit) smaller but a lot faster to start (excluding about 900 files).

@kayhayen Could you take a second to review the NUITKA_EXCLUDE_FILES list please, to make sure I'm not excluding files too broadly ?

**Comment by kayhayen** [comment]
@deajan The exlusions seem to not be universally possible, but I understand that they might make sense most of the time. I don't think any of them belongs to default behavior of Nuitka.

But one thing that would really advance Nuitka there is to start compiling standard library by default in a way that allows to see that e.g. `decimal` or `sqlite3` are not really used. But isn't that something for @JorjMcKie hinter to brilliantly detect? Or are there cases, where things will be used, but when then they are not present, it's OK too?

**Comment by JorjMcKie** [comment]
@kayhayen, @deajan - yes, the hinting logic does detect whether things like sqlite3 are used. Currently I do not bother logging uses of built-in modules, because I cannot prevent them from being compiled anyway. BTW non-built-ins like ``os``, ``site``, ``types`` **are** already dropped if not used.
But reverting this would be a trivial change.
On occasion, I have also been considering, whether I should delete things like `tcl86t.dll`, `tk86t.dll`, `sqlite3.dll`, ... during hinted compilation if the resp. modules were not imported and / or ``tk-inter`` plugin was not used. Those 3 alone are more than 4 MB on 64bit.

Maybe, @deajan, accessing the JSON file output from ``get-hints.py`` would be an option. Here is an example from a very basic script using these imports:
```python
import math
import sys
import sqlite3
...
```
... results in JSON file:
```python
{
    "calls": [
        ["_sqlite3", "_sqlite3"],
        ["_sqlite3.*", "_sqlite3"],
        ["collections", "collections"],
        ["collections.abc", "collections"],
        ["datetime", "datetime"],
        ["sqlite3", "sqlite3"],
        ["sqlite3.dbapi2", "sqlite3.dbapi2"],
        ["sqlite3.dbapi2.*", "sqlite3.dbapi2"]
    ],
    "files": ["_sqlite3", "collections", "datetime", "sqlite3", "sqlite3.dbapi2"]
}
```
The list ``"files"`` (actually imported modules) list could be used to make those decisions. The JSON filename can be derived from the ``dist`` folder name in a deterministic way ...

**Comment by JorjMcKie** [comment]
The compile log for the above script looks like this:
```
NUITKA is compiling 'trial1.py' with these options:
 --standalone
 --remove-output
 --experimental=use_pefile
 --recurse-none
 --disable-dll-dependency-cache

Nuitka:INFO:User plugin 'hinted-mods.py' is being loaded.
Nuitka:INFO:'hinted-mods.py' is adding the following options:
Nuitka:INFO:--recurse-to for 5 imported modules.
Nuitka:INFO:
Nuitka:INFO:drop os
Nuitka:INFO:drop types
Nuitka:INFO:drop site
Nuitka:WARNING:Not recursing to unused 'collections'.
Nuitka:WARNING:Not recursing to unused 'datetime'.
Nuitka:WARNING:Not recursing to unused 'sqlite3.dbapi2'.
Nuitka:INFO:Compile time 30 seconds.
```

**Comment by deajan** [comment]
Hmmm. Interesting.
I could indeed leave a "standard" exclusion list which can be overriden by --hints-log=file.json.
I'll have a look later with one of my projects, but for now I can't use hinted compilation with that one because of #9.
Anyway, it's already pretty usable for me in the current shape.
I'll continue optimizing my project an see whether I can integrate hinted compilation in my toolchain.

Thinking of, nuitka utilities is a collection of scripts that isn't easy for a beginner (example: PySimpleGUI not distributed with utilities). What about creating a wrapper (GUI & CLI menu) for all scripts, and maybe add PySimpleGUI directly so a simple git clone is sufficient to make things work out of the box ?
Also, I'd like to add a full CLI interface so everything can be integrated without having to play with a GUI.
Any thoughts ?

**Comment by JorjMcKie** [comment]
As per #9:
Hinted compilation is now able to also check implicit imports. A module will be accepted if it occurs as an implicit import for package_name / module_name.

**Comment by JorjMcKie** [comment]
> @kayhayen, @deajan - yes, the hinting logic does detect whether things like sqlite3 are used. Currently I do not bother logging uses of built-in modules, ...

To clarify this remark:
When talking of ``buitl-in`` modules, this is meant in the strict sense. E.g. ``sys``, ``math`` are built-ins, ``os``, ``decimal``, ``sqlite3``, ``tkinter``, ... are **not**, and are consequently **already contained** in the hinting JSON file.

**Pull request merged**
